### ISSUE TITLE
nmm crashes when launched

### ISSUE THREAD

**Issue by swagpunchabitch** [Nexus-Mods/Nexus-Mod-Manager#830] opened 2019-06-04 22:22 UTC
[TraceLog20190604162103.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3254695/TraceLog20190604162103.txt)

**Comment by a19957143** [comment] 2019-06-06 17:51
Same thing here. HELP PLEASE!!!!!!!!!!!!!!!!!!!!!!!!
Tracing an Unhandled Exception:
        Exception: 
Message: 
	El método 'Parse' en el tipo 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' del ensamblado 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' no tiene una implementación.
Full Trace: 
	System.TypeLoadException: El método 'Parse' en el tipo 'Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser' del ensamblado 'Fallout3.XmlScript, Version=0.70.7.0, Culture=neutral, PublicKeyToken=null' no tiene una implementación.

**Comment by robboten** [comment] 2019-06-08 12:07
same here

**Comment by robboten** [comment] 2019-06-08 12:24
Uninstall/reinstall fixed it

**Comment by a19957143** [comment] 2019-06-08 14:47
Robboten are you sure? I already reinstalled in order 2 times. I havent uninstalled yet, because I have like 300 mods instaled with Skyrim. I wil try.

**Comment by squid-box** [comment] 2019-06-09 10:54
This issue is a duplicate of #728, there's detailed steps there to fix it - but you will need to uninstall (it won't remove your mods as long as you don't delete configuration files or change directories).

**Closed as completed** 2019-09-16 07:04 UTC
Labels: duplicate
