### ISSUE TITLE
Nexus Mod manager wont download via "Download with Mod manager".

### ISSUE THREAD

**Issue by Jaber1028** [Nexus-Mods/Nexus-Mod-Manager#228] opened 2018-01-16 16:56 UTC
Nothing happens, My NMM does not change. I switched drives on my pc and now Does not work

**Comment by Nubbie** [comment] 2019-05-26 13:39
@squid-box Duplicate of #132

**Comment by squid-box** [comment] 2021-03-07 21:03
This is likely just a problem with the nxm url association. As there have been changes to how we set that up since this was reported, I'm closing this issue as outdated.

If it's still an ongoing issue, please create a new issue with relevant information like version used and preferably a TraceLog you've gotten generated when trying to associate NMM with nxm urls.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:03 UTC
