### ISSUE TITLE
No Download

### ISSUE THREAD

**Issue by Jackdadipper** [Nexus-Mods/Nexus-Mod-Manager#142] opened 2017-08-06 21:44 UTC
When I try to download a mod for Fallout New Vegas (have not tried other games) it completely fails to download. The mod does not even appear in the download tab, it is as if I didn't even press the button. My version of Nexus Mod Manager in up to date, I am logged in both on windows and the manager, and I have tried the run as administrator to toggle Associate with NXM URLs and disabling my firewalls while trying to download.

**Comment by Sulhir** [comment] 2017-08-26 16:10
I have this exact problem with all mods for all games.  I believe for me it is because I have both the games and NMM installed to a hard drive that does not have my Windows installation on it.  Windows hardly knows my files are there (indexing and searches do not search this hard drive for whatever reason) and I believe this is why.
I can still download mods manually and add them via the "add mod from file/url" button.  I'd like to be able to test the "add mod from URL" function but it is looking for some odd link format that I do not understand.

**Comment by squid-box** [comment] 2021-03-07 20:49
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 20:49 UTC
