### ISSUE TITLE
NMM won't load, even after soft reset. 

### ISSUE THREAD

**Issue by Hainesey** [Nexus-Mods/Nexus-Mod-Manager#513] opened 2018-07-20 17:38 UTC
[TraceLog20180720181541.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2214864/TraceLog20180720181541.txt)

**Comment by squid-box** [comment] 2018-07-20 17:47
Duplicate of #389 , just grab the latest version and you should be good to go.

**Closed as completed** 2018-07-24 08:49 UTC
Labels: duplicate
