### ISSUE TITLE
When i click "Download Using NMM" nothing happens, NMM doesn't download it.

### ISSUE THREAD

**Issue by Gerald321** [Nexus-Mods/Nexus-Mod-Manager#172] opened 2017-10-20 21:20 UTC
Title says it all.

**Comment by Nubbie** [comment] 2019-05-26 13:38
@squid-box Duplicate of #132

**Comment by squid-box** [comment] 2021-03-07 21:03
This is likely just a problem with the nxm url association. As there have been changes to how we set that up since this was reported, I'm closing this issue as outdated.

If it's still an ongoing issue, please create a new issue with relevant information like version used and preferably a TraceLog you've gotten generated when trying to associate NMM with nxm urls.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:03 UTC
