### ISSUE TITLE
Mod will not install

### ISSUE THREAD

**Issue by GamerFoxNeumann** [Nexus-Mods/Nexus-Mod-Manager#591] opened 2018-08-31 09:15 UTC
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Can't install a mod, mod problem states:
SA80 British Rifle (L85 and L86) - SA80 V4.2 // A problem occurred during install: 
The process cannot access the file 'C:\Users\Aaron Thomas Neumann\AppData\Local\Temp\NexusModManager\tempfile_mvo1al0z.j0h' because it is being used by another process.
The mod was not installed. // Install // 

**Environment**
- NMM version: _0.65.9_
- Mod(s) used: https://www.nexusmods.com/fallout4/mods/24619?tab=files

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by GamerFoxNeumann** [comment] 2018-08-31 13:37
SA80 British Rifle (L85 and L86) - SA80 V4.2 // A problem occurred during install: 
The process cannot access the file 'C:\Users\Aaron Thomas Neumann\AppData\Local\Temp\NexusModManager\tempfile_0tv4jl0z.4zo' because it is being used by another process.
The mod was not installed. // Install // 

I've checked the latest trace logs and they don't tell me anything. :\

**Comment by squid-box** [comment] 2018-08-31 14:11
You could force the creation of a trace log, they should have some info in them. Check [this wiki page](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log).

**Comment by GamerFoxNeumann** [comment] 2018-08-31 14:57
[TraceLog20180831085535.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2340528/TraceLog20180831085535.txt)
Well, here's the tracelog... hope it helps...

**Comment by squid-box** [comment] 2018-08-31 16:27
Unfortunately nothing is logged when this occurs (I might try to fix that). 

Are you getting this issue consistently (but with different temp filenames)?

Does it happen with any other mod?

**Comment by GamerFoxNeumann** [comment] 2018-08-31 16:30
Not really, usually whenever I can't install something it usually is because of 7zip compression, not temp files...

... and I keep getting this problem with various temp files. :\

**Comment by squid-box** [comment] 2018-08-31 19:09
So I can't reproduce the problem on my machine with the mod you've linked. 

I'll try to add some relevant logging, but it's not something like you've run out of space on the drive where your temp folder is, or running two instances of NMM, or something like that?

**Comment by GamerFoxNeumann** [comment] 2018-09-01 00:43
Deleted a lot of old mods that I don't use, usually vastly outdated ones... and I've got 2.5gigs of space on C drive...

I've asked the mod author if he has heard anything on his end... because this is frankly ridiculous.

SA80 British Rifle (L85 and L86) // A problem occurred during install: 
The process cannot access the file 'C:\Users\Aaron Thomas Neumann\AppData\Local\Temp\NexusModManager\tempfile_vgg52l3l.dk0' because it is being used by another process.
The mod was not installed. // Install //

**Comment by GamerFoxNeumann** [comment] 2018-09-01 02:39
Handmade Anti-Materiel Rifle -4K // A problem occurred during install: 
The process cannot access the file 'C:\Users\Aaron Thomas Neumann\AppData\Local\Temp\NexusModManager\tempfile_oqp1il0z.ufm' because it is being used by another process.
The mod was not installed. // Install // 

... now I'm getting it on other mods...

**Comment by GamerFoxNeumann** [comment] 2018-09-01 02:49
Again... :\ This is weird because I never had this problem before...
Handmade Anti-Materiel Rifle -4K // A problem occurred during install: 
The process cannot access the file 'C:\Users\Aaron Thomas Neumann\AppData\Local\Temp\NexusModManager\tempfile_yy4lxzl1.hoi' because it is being used by another process.
The mod was not installed. // Install //

**Comment by GamerFoxNeumann** [comment] 2018-09-01 03:50
Now with the anti-materiel rifle, it's saying that the mod is installed but the ESL isn't showing up. :\

**Comment by squid-box** [comment] 2021-03-08 21:11
Sorry for leaving this lying around for so long, there's just nothing to do unless I can reproduce it on my end.
I'm closing it now, but please create a new issue if you're still seeing this problem.

**Closed as completed by squid-box** 2021-03-08 21:11 UTC
