### ISSUE TITLE
trace log 

### ISSUE THREAD

**Issue by tico963** [Nexus-Mods/Nexus-Mod-Manager#530] opened 2018-07-29 03:52 UTC
trace log problem

i tried to install the mod but it occured with this error

**Environment**
- NMM version: 0.65.2
- Mod(s) used: https://www.nexusmods.com/skyrim/mods/38326/

Trace file has been created: TraceLog20180729104321.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Games\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Games\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) SkyrimSE
Game Mode Factory Selected: Skyrim Special Edition (SkyrimSE)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim Special Edition (SkyrimSE)
    Installation Path: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition
    Install Info Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info
    Mod Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
    Mod Cache Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods\cache
    Mod Download Cache: C:\Games\Nexus Mod Manager\SkyrimSE\Mods\downloads
    Overwrite Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info\overwrites
    Virtual Install Path: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Games\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Games\Nexus Mod Manager\GameModes
            Checking: SkyrimSE.CSharpScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.CSharpScript.SkyrimSECSharpScriptType
            Checking: SkyrimSE.XmlScript.dll
                Initializing: Nexus.Client.Games.SkyrimSE.Scripting.XmlScript.SkyrimSEXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Games\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: C:\Games\Nexus Mod Manager\SkyrimSE\Mods
        Found: C:\Games\Nexus Mod Manager\SkyrimSE\Mods\Seranaholic v1.8-38326-1-8.7z
            Registered.
    Found 1 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: C:\Games\Nexus Mod Manager\SkyrimSE\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
    Found Seranaholic v1.8-38326-1-8.7z...OK
Initializing Plugin Management Services...
    Initializing Plugin Registry...
        Discovering Managed Plugins...
            Discovering Plugins...
                Looking in: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data
                Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dawnguard.esm
                Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dragonborn.esm
                Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\HearthFires.esm
                Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Skyrim.esm
                Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Update.esm
            Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dawnguard.esm
                Registered.
            Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dragonborn.esm
                Registered.
            Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\HearthFires.esm
                Registered.
            Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Skyrim.esm
                Registered.
            Found: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Update.esm
                Registered.
        Found 5 managed plugins.
    Initializing Plugin Order Log...
        Loading Plugin Order...
            Getting Plugin Load Order from the load order manager...
            Loading C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Skyrim.esm (IsNull=False)
            Loading C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Update.esm (IsNull=False)
            Loading C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dawnguard.esm (IsNull=False)
            Loading C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\HearthFires.esm (IsNull=False)
            Loading C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dragonborn.esm (IsNull=False)
    Initializing Active Plugin Log...
    Initializing Plugin Manager...
Initializing Activity Monitor...
Initializing Mod Activation Monitor...
Initializing Mod Manager...
Upgrading replaced Mods...
Uninstalling missing Mods...
Loading mods that are queued to be added.
Launch Commands:
    Plain Command: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\SkyrimSE.exe (IsNull=False)
    SKSE Command: C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\skse64_loader.exe (IsNull=False)
    Custom Command:  (IsNull=True)
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
    Wrye Bash Command:  (IsNull=False)
    SSEEdit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Loading Plugins into Plugin List: 5
    Loading: Skyrim.esm (C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Skyrim.esm) (False)
    Loading: Update.esm (C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Update.esm) (False)
    Loading: Dawnguard.esm (C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dawnguard.esm) (False)
    Loading: HearthFires.esm (C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\HearthFires.esm) (False)
    Loading: Dragonborn.esm (C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\Dragonborn.esm) (False)
Setting up listener on Nexus Mod Manager-SkyrimSEIpcServer/SkyrimSEListener at 2018-07-29 10:43:24
Running Application.

Tracing an Unhandled Exception:
Exception: 
Message: 
	Access to the path 'C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\meshes\actors\character\FaceGenData\FaceGeom\Dawnguard.esm' is denied.
Full Trace: 
	System.UnauthorizedAccessException: Access to the path 'C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\meshes\actors\character\FaceGenData\FaceGeom\Dawnguard.esm' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Nexus.Client.Util.FileUtil.CreateDirectory(String p_strPath)
   at Nexus.Client.ModManagement.VirtualModActivator.AddFileLink(IMod p_modMod, String p_strBaseFilePath, String p_strSourceFile, Boolean p_booIsSwitching, Boolean p_booIsRestoring, Boolean p_booHandlePlugin, Int32 p_intPriority)
   at Nexus.Client.ModManagement.ModLinkInstaller.AddFileLink(IMod p_modMod, String p_strBaseFilePath, String p_strSourceFile, Boolean p_booIsSwitching, Boolean p_booHandlePlugin)
   at Nexus.Client.ModManagement.ModLinkInstaller.AddFileLink(IMod p_modMod, String p_strBaseFilePath, String p_strSourceFile, Boolean p_booIsSwitching)
   at Nexus.Client.ModManagement.LinkActivationTask.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    3 () 
        Aborted

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by zeb202** [comment] 2018-07-31 05:08
I had the same problem. Go to the Nexus Mod Manager folder in your program files. Then in that folder go to the uninstall folder and run the .exe file. The reinstall NMM.

**Comment by tico963** [comment] 2018-07-31 16:16
thanks but its still got problem, the NMM still send trace log

**Comment by squid-box** [comment] 2021-03-07 21:17
The crash is due to problems with file access: 

`Access to the path 'C:\Games\Bethesda Softworks\The Elder Scrolls V Skyrim - Special Edition\Data\meshes\actors\character\FaceGenData\FaceGeom\Dawnguard.esm' is denied.`

The only suggestion I have is to try running NMM with elevated privileges, or make sure you (your Windows user) has proper access to the game install directory.

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:17 UTC
