### ISSUE TITLE
Wrong Mod Title and Author SkyrimSE

### ISSUE THREAD

**Issue by AmarylisVS** [Nexus-Mods/Nexus-Mod-Manager#13] opened 2016-11-08 06:53 UTC
When I install a mod with "Add mod from File" i get the wrong mod title

If i add "Autoharvest" NMM shows "Nocturnals Craftable Armor -CBBE friendly has been added" in Downladmanager and after installing under mods

"Bandolier - Bags and Pouches" becomes "Ravien - Queen of the Bolt has been added"

and so on

**Comment by DuskDweller** [comment] 2016-11-08 08:40
Are you adding Skyrim mods to the Skyrim SE game mode? If so, then that's bound to happen, cause that mode only handles Skyrim SE filenames and file IDs, thus when communicating with the server you get the wrong results.
What you can do to alleviate the issue is to go in the NMM Settings menu and disable "Allow NMM to update mod names" .

**Comment by AmarylisVS** [comment] 2016-11-08 14:44
Hi,

`Are you adding Skyrim mods to the Skyrim SE game mode?`
Yes - some mods from Skyrim work with SSE

Disabling "Allow NMM to update mod names" doesn´t work.

I will change the Titles by hand

**Comment by DuskDweller** [comment] 2016-11-16 01:40
Also disable "Add missing mod info".
But keep in mind this won't fix mod names/info that have already been modified.

**Closed as completed** 2018-05-24 22:52 UTC
Labels: invalid
