### ISSUE TITLE
Cannot open NMM

### ISSUE THREAD

**Issue by paperear34** [Nexus-Mods/Nexus-Mod-Manager#354] opened 2018-05-29 05:14 UTC
I just tried downloading Nexus on my Omen Gaming Laptop but I can't seem to get it to run. I only need it for FO4 I never had an issue running NMM on other computers but times change. You have probably seen this before but I don't understand what the issue is. Please help if possible!

Trace file has been created: TraceLog20180529001013.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files (x86)\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: Morrowind.ModScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Morrowind.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Oblivion.ModScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Oblivion.ModScript.dll: cannot find dependency ModScript, Version=1.1.6689.33168, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files (x86)\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Searching for the installation paths of:
    Breaking Wheel (BreakingWheel)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\545890\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls (DarkSouls)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211420\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dark Souls 2 (DarkSouls2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236430\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age (DragonAge)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\17450\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Dragon Age 2 (DragonAge2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    Dragon's Dogma (DragonsDogma)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\367500\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Fallout 3 (Fallout3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22300\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout3\Installed Path
                Found 
            Returned:  (IsNull=True)
    Fallout 4 (Fallout4)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\377160\Installed
                Getting Steam install folder.
                Fallout4 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Fallout4\Installed Path
                Found C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\
            Returned: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\ (IsNull=False)
    Fallout: New Vegas (FalloutNV)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22380\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\FalloutNV\Installed Path
                Found 
            Returned:  (IsNull=True)
    Legend of Grimrock (Grimrock)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\207170\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Morrowind (Morrowind)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22320\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    No Man's Sky (NoMansSky)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\275850\Installed
                Getting Steam install folder.
                Found c:\program files (x86)\steam\steamapps\common\No Man's Sky
            Returned: c:\program files (x86)\steam\steamapps\common\No Man's Sky (IsNull=False)
    Oblivion (Oblivion)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\22330\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Oblivion\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim (Skyrim)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\72850\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim\Installed Path
                Found 
            Returned:  (IsNull=True)
    Skyrim Special Edition (SkyrimSE)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\489830\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\SkyrimSE\Installed Path
                Found 
            Returned:  (IsNull=True)
    Starbound (Starbound)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\211820\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    State of Decay (StateOfDecay)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\241540\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Elder Scrolls Online (TESO)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Zenimax_Online\Launcher\InstallFolder
                Found 
            Returned:  (IsNull=True)
    War Thunder (WarThunder)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\236930\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    The Witcher 2 (Witcher2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\20920\Installed
                Getting install folder from Uninstall.
                Found 
            Checking: HKEY_LOCAL_MACHINE\Software\Wow6432Node\CD Projekt RED\The Witcher 2\InstallFolder
                Found 
            Returned:  (IsNull=True)
    The Witcher 3 (Witcher3)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\292030\Installed
                Getting install folder from Uninstall.
                Found 
            Getting GOG install folder.
            Returned:  (IsNull=True)
    World of Tanks (WorldOfTanks)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Returned:  (IsNull=True)
    XCOM 2 (XCOM2)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\268500\Installed
                Getting Steam install folder.
                XCOM2 is not installed in standard directory. Checking steam config.vdf...
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    X Rebirth (XRebirth)
        Checking Last Installation Path...
            Returned:  (IsNull=True)
        Asking Game Mode...
            Checking for steam install: HKEY_CURRENT_USER\Software\Valve\Steam\Apps\2870\Installed
                Getting install folder from Uninstall.
                Found 
            Returned:  (IsNull=True)
    Starting search.
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
    Loading NoMansSky: Supported
Determining Game Mode: (From Selection Form) Fallout4
Game Mode Factory Selected: Fallout 4 (Fallout4)
Creating Game Mode mutex (Attempt: 0)

Tracing an Unhandled Exception:
Running Threads (1)
    5 () 
        Aborted
        Exception: 
Message: 
	Value cannot be null.
Parameter name: v1
Full Trace: 
	System.ArgumentNullException: Value cannot be null.
Parameter name: v1
   at System.Version.op_LessThan(Version v1, Version v2)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.InitializeManager()
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeBase.SetupPluginManagement(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   at Nexus.Client.Games.Fallout4.Fallout4GameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   at Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by squid-box** [comment] 2018-05-29 06:13
It looks to be a duplicate of #300, NMM can't find the Fallout 4 executable. 

Seems everyone having this problem are trying to trick NMM into managing Fallout 4VR.

**Comment by paperear34** [comment] 2018-05-29 06:30
Ahaha. Duh, sorry that is so obvious after you said it. I have no clue why I didn't think of it. So I had to do a work around because my game stopped working after on of the updates a long time ago. I just recently decided to get it up and running again and the only fix that worked for me was changing the name of the exe file to the launcher and renaming the launcher.
![fo4](https://user-images.githubusercontent.com/39720512/40641578-cb13122e-62df-11e8-8de1-a2b5356fad1e.jpg)

**Comment by paperear34** [comment] 2018-05-29 06:32
Better screenshot
![fo42](https://user-images.githubusercontent.com/39720512/40641663-1146892e-62e0-11e8-8478-341e3ddea052.jpg)

**Comment by squid-box** [comment] 2018-05-29 06:40
So in your case I'd say to make a copy of the larger file and name it Fallout4.exe, and NMM should find that and let you start it.

**Comment by paperear34** [comment] 2018-05-29 06:54
Now I am stuck here...
![fo43](https://user-images.githubusercontent.com/39720512/40642615-3ccc1840-62e3-11e8-94a9-47586b113905.jpg)

**Comment by squid-box** [comment] 2018-05-29 06:57
Have you tried starting NexusClient as an administrator? (Right click and select _Run as administrator_)

**Comment by paperear34** [comment] 2018-05-29 07:01
Yeah that seems to at least kind of work
![fo44](https://user-images.githubusercontent.com/39720512/40642948-2b322fe2-62e4-11e8-8d8c-b50251617f76.jpg)

**Comment by paperear34** [comment] 2018-05-29 07:06
And is operational as far as I can tell. I will get back to you if any new issues come forth

**Closed as completed** 2018-06-01 05:53 UTC
Labels: duplicate
