### ISSUE TITLE
NMM Crashes When Selecting Settings

### ISSUE THREAD

**Issue by Zaikusu** [Nexus-Mods/Nexus-Mod-Manager#1123] opened 2021-04-04 10:49 UTC
Recently installed and setup NMM for Fallout 4, and selecting the Settings tab crashes the entire program. This happens no matter what and at all times should I press the Settings tab. I do not know what is causing this issue and looking on the forums for common issues did not produce any solutions.
[TraceLog20210404034307.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6254374/TraceLog20210404034307.txt)

**Comment by IanMunster** [comment] 2021-04-05 00:42
**Description:**
I have the same issue, also for Fallout 4. (Program Crashes as soon as I hit the Settings-button)

**Enviroment:**
I'm on a Win8.1 machine
Using NMM 0.80.4
I presume it has nothing to do with my mods, because the crash happened with an empty modlist. If the modlist is needed, I will reply as soon as possible

**Reproduce:**
Click on the "Settings"-button when using the Fallout 4 Manager

**Tracelog:**
[TraceLog20210405023935.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/6255761/TraceLog20210405023935.txt)

**Comment by IanMunster** [comment] 2021-04-05 00:45
This report is duplicate with #1122 #1121

**Comment by Hault360** [comment] 2021-04-05 01:11
I'm having the same issue and it's preventing me from fixing an issue I'm having with SkyUI, please does anyone have a solution.

**Comment by DuskDweller** [comment] 2021-04-05 01:46
Is any of you on the Discord server for a quick test ?

**Comment by sairosol** [comment] 2021-04-05 03:58
I have the same issue. exact same trace log file aswell

on windows 10, for fallout 4 vr
what's the discord?

**Comment by DuskDweller** [comment] 2021-04-05 09:27
> 
> 
> I have the same issue. exact same trace log file aswell
> 
> on windows 10, for fallout 4 vr
> what's the discord?

There's a Discord button on the upper right corner of the NMM top bar.

**Comment by DuskDweller** [comment] 2021-04-06 15:26
Fixed in 0.80.5 !

**Closed as completed by DuskDweller** 2021-04-06 15:26 UTC
Labels: bug

**Comment by IanMunster** [comment] 2021-04-06 22:23
Using v0.80.6 on Win8.1 and its fixed for me!
Many thanks for the quick fix!
