### ISSUE TITLE
Nexus Crashing On Load Up

### ISSUE THREAD

**Issue by Calmetz** [Nexus-Mods/Nexus-Mod-Manager#987] opened 2020-04-07 21:16 UTC
The other day I was working on a heavily modded Fallout New Vegas and then today I went to continue my work in NMM and it just wouldn't open. As soon as it tried, it would give me an error log. I looked into the log and it seems that some scripts for Fallout 3 and Fallout 4 in the NMM Game Modes directory aren't being read or something, however I have no clue how to fix this. Help would be greatly appreciated. Thank you for your time! I will post my trace log below.

[TraceLog20200407171128.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/4447019/TraceLog20200407171128.txt)

**Comment by squid-box** [comment] 2021-03-07 22:31
A year later, this looks to be a corrupted installation of NMM: it's failing to load Fallout4.XmlScript.dll or more likely a dependency that one has on Antlr3.Runtime.dll (as seen a little higher in your TraceLog where it fails to load that same dependency for the Fallout3.XmlScript.dll.

The only thing I can recommend is trying to reinstall or update NMM and see if the issue is resolved.
Closing issue due to it being nearly a year old, but please feel free to reopen if you're still seeing issues.

**Closed as completed by squid-box** 2021-03-07 22:31 UTC
Labels: installation
