### ISSUE TITLE
encountered some error

### ISSUE THREAD

**Issue by Aerowings** [Nexus-Mods/Nexus-Mod-Manager#377] opened 2018-06-06 16:08 UTC
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
cant open it
[TraceLog20180604163324.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077106/TraceLog20180604163324.txt)
[TraceLog20180606014039.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077107/TraceLog20180606014039.txt)
[TraceLog20180606014114.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077108/TraceLog20180606014114.txt)
[TraceLog20180606014229.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077109/TraceLog20180606014229.txt)
[TraceLog20180606014251.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077110/TraceLog20180606014251.txt)
[TraceLog20180606014304.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077111/TraceLog20180606014304.txt)
[TraceLog20180606115056.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077112/TraceLog20180606115056.txt)
[TraceLog20180606230416.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2077113/TraceLog20180606230416.txt)

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment] 2018-06-09 07:43
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting (in your case there's a few different ones, like changing the size of the UI, just starting NMM)), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:43 UTC
Labels: duplicate
