### ISSUE TITLE
stuttering and game launches twice now. since install there is now a slight constant stutter in game and now it launches the game twice with one custom loader setup i had on previous nmm 65.2.

### ISSUE THREAD

**Issue by Singleminded2020** [Nexus-Mods/Nexus-Mod-Manager#739] opened 2019-05-13 18:31 UTC
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_
Slight stutter in game since install of 0.70.1 and launches game twice.

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_
nmm 0.70.1 new api release
_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_
just click the nexus custom loader option to start game. it brings up skyrim initial window with options and play and such. and skyrim that runs in background. i have to cancel 1 then play the other. while the stutter persists.

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by Singleminded2020** [comment] 2019-05-13 18:34
Edit: If i use the skse_loader.exe outside of nmm it loads as intended without stutter and without loading twice.

**Comment by squid-box** [comment] 2019-05-13 18:43
The multiple launch is likely caused by #732, which will be fixed in the next version. Hopefully the stutter is resolved by not launching multiple instances.

**Comment by Singleminded2020** [comment] 2019-05-13 18:53
i really do appreciate you guys keeping nmm going. vortex is just...not very intuitive and very restrictive. tried twice to get vortex to work the way i want and it just caused tons of issues. MO2 is better by far but a bit too convoluted for my taste. nmm is just much easier to use and more flexible.

**Comment by squid-box** [comment] 2019-05-13 21:13
0.70.2 is released now, including a fix for this. Please check if your problems are resolved in this version.

**Comment by squid-box** [comment] 2019-09-16 13:34
Closing due to inactivity.

**Closed as completed by squid-box** 2019-09-16 13:34 UTC
Labels: need info
