### ISSUE TITLE
Client won't download mods from website

### ISSUE THREAD

**Issue by matthew-field** [Nexus-Mods/Nexus-Mod-Manager#146] opened 2017-08-12 08:31 UTC
When I click the "Download (NMM)" option on the website, nothing happens on the mod manger. There's the usual brief loading icon (as well as the pop-up if more than one mod/dlc is required) appears on the website and that all behaves normally but when I go to the manager there's nothing in the "Download Mangager" queue and the file doesn't download at all.

**Comment by Sulhir** [comment] 2017-09-05 15:56
Same thing here, likely due to the fact that I have NMM installed and operating from a different drive than Windows (although the same drive with the games and Steam).

**Comment by BlackTearAngel1999** [comment] 2017-11-22 03:20
I click on the mod and it starts to download, but it always ends in an error and never completes itself.

**Comment by Nubbie** [comment] 2019-05-26 13:38
@squid-box Duplicate of #132

**Comment by squid-box** [comment] 2021-03-07 21:03
This is likely just a problem with the nxm url association. As there have been changes to how we set that up since this was reported, I'm closing this issue as outdated.

If it's still an ongoing issue, please create a new issue with relevant information like version used and preferably a TraceLog you've gotten generated when trying to associate NMM with nxm urls.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:03 UTC
