### ISSUE TITLE
Crashes on startup; runs only in background and not on desktop.

### ISSUE THREAD

**Issue by runningfree984** [Nexus-Mods/Nexus-Mod-Manager#582] opened 2018-08-24 22:35 UTC
**Describe the bug** 
I can get NMM to install and detect my games no problem. But sometimes when I start it it just crashes and prompts me to open the crashlog, and sometimes the program just runs in the background where I can't access it and I have to shut it down via the Task Manager. I have attached all of the TraceLogs since I tried getting it working on Wednesday.

**Environment**
- NMM version: _0.65.2 (whatever the latest version is)
- Mod(s) used: None yet

[TraceLog20180822175411.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320084/TraceLog20180822175411.txt)
[TraceLog20180822175811.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320085/TraceLog20180822175811.txt)
[TraceLog20180822175931.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320086/TraceLog20180822175931.txt)
[TraceLog20180822180027.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320087/TraceLog20180822180027.txt)
[TraceLog20180822180241.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320088/TraceLog20180822180241.txt)
[TraceLog20180822180308.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320089/TraceLog20180822180308.txt)
[TraceLog20180822180351.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320090/TraceLog20180822180351.txt)
[TraceLog20180823185238.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320091/TraceLog20180823185238.txt)
[TraceLog20180823200219.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320092/TraceLog20180823200219.txt)
[TraceLog20180824182631.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320093/TraceLog20180824182631.txt)
[TraceLog20180824182849.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2320094/TraceLog20180824182849.txt)

**Comment by squid-box** [comment] 2018-08-25 05:19
Duplicate of #389, download 0.65.9 (currently latest version) from GitHub: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by runningfree984** [comment] 2018-08-25 18:29
Thanks so much. It seems to be working fine now. I will update if I encounter any more problems.

**Closed as completed** 2019-02-16 07:29 UTC
Labels: duplicate
