### ISSUE TITLE
Trace log error fallout 4

### ISSUE THREAD

**Issue by Henlar123** [Nexus-Mods/Nexus-Mod-Manager#597] opened 2018-09-06 13:32 UTC
Hi everyone i am having problems with NMM with a trace log error, i have tried solving it and searching a lot, but i couldnt find a solution

I already tried re-installing NMM to the latest version, deleteing and changing codes in the folder Black tree Gaming and i still have the same problem.

- NMM version: _0.65.2_

This is the message i get at the end of the tracer log

Message: 
	El valor no puede ser nulo.
Nombre del parámetro: v1
Full Trace: 
	System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: v1
   en System.Version.op_LessThan(Version v1, Version v2)
   en Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.InitializeManager()
   en Nexus.Client.Games.Gamebryo.GamebryoGameModeBase.SetupPluginManagement(FileUtil p_futFileUtility)
   en Nexus.Client.Games.Fallout4.Fallout4GameMode..ctor(IEnvironmentInfo p_eifEnvironmentInfo, FileUtil p_futFileUtility)
   en Nexus.Client.Games.Fallout4.Fallout4GameModeFactory.InstantiateGameMode(FileUtil p_futFileUtility)
   en Nexus.Client.Games.Gamebryo.GamebryoGameModeFactory.BuildGameMode(FileUtil p_futFileUtility, ViewMessage& p_imsWarning)
   en Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   en Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   en Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   en Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart(Object obj)

any help would be greatly aprecciated

**Comment by squid-box** [comment] 2018-09-06 15:38
Duplicate of #300, look there for potential fixes. Either you've used some unofficial patch/crack that "broke" your Fallout4 exe, or you've moved some files around.

**Closed as completed** 2019-02-15 17:29 UTC
Labels: duplicate
