### ISSUE TITLE
Profiles not working

### ISSUE THREAD

**Issue by llewelynrex** [Nexus-Mods/Nexus-Mod-Manager#16] opened 2016-11-18 08:12 UTC
I'm running Skyrim SE on Windows 10 64bit. I'm trying to create some profiles to easily switch mod configurations. I currently have two profiles: Base and Main. I change to Main, activate some mods and then save the profile. When switching back to Base, the mods which were activated (or deactivated) are active (inactive) in Base as well and the active mod count is changed. For some reason the profiles aren't saving properly on my machine. Tried running as Administrator as well. No joy.

Not sure whether this is an issue on my local system or whether it's a problem elsewhere as well.

**Comment by llewelynrex** [comment] 2016-11-18 12:01
B.t.w. I'm running Nexus Mod Manager 0.63.9.

**Comment by DuskDweller** [comment] 2016-11-18 19:22
Thanks for the feedback, I'll look into this.

**Comment by llewelynrex** [comment] 2016-11-18 20:39
No problem. Just let me know if you need more information. And thanks for the Mod Manager. It makes managing the mods much simpler. :)

**Comment by metaphorset** [comment] 2016-11-30 19:53
There are many reports on this. The longest thread I found on the nexus beta forum is this one:
https://forums.nexusmods.com/index.php?/tracker/issue-66570-nexus-mod-manager-not-maintaining-profiles/

I can confirm that 0.60.21 is the last version that handled profiles correctly.

**Comment by Okimo** [comment] 2016-12-24 06:42
Actually last working version with profiles was "0.63.6" :)

**Comment by L3zl13** [comment] 2016-12-25 20:17
I use 0.63.7. Profiles still worked in this.

**Comment by Freakness109** [comment] 2017-01-04 14:58
#22 should fix it.

**Comment by david-m-m** [comment] 2017-12-09 09:13
Seems still to be broken in 0.63.14 (as of Dec-2018). Is there any chance that the relatively simple fix #22 will make it to the next release?

**Comment by squid-box** [comment] 2018-05-24 22:54
With #22 merged in January 2017 and with no more comments here, I'm going to close this issue assuming the problem is fixed.

**Closed as completed by squid-box** 2018-05-24 22:54 UTC
