### ISSUE TITLE
crasch report....i can't download my mod's

### ISSUE THREAD

**Issue by Nikiquentin** [Nexus-Mods/Nexus-Mod-Manager#367] opened 2018-06-03 18:33 UTC
Sometime I can't launch nexus and sometime i can't download because it crasch

I tried to download a lot of mods but everytime i get a crasch report 

[TraceLog20180603202551.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2066239/TraceLog20180603202551.txt)

It's just an exemple...It's the first time i use Nexus and this is very annoying please help !

**Comment by squid-box** [comment] 2018-06-09 07:44
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:44 UTC
Labels: duplicate
