### ISSUE TITLE
NMM "being used by another process"

### ISSUE THREAD

**Issue by Lonewolf575** [Nexus-Mods/Nexus-Mod-Manager#364] opened 2018-06-02 20:22 UTC
Upon opening up NMM for the first time after reinstalling it, I got an error message after selecting FO4 to mod. Running in Admin mode only gives me the choice to change my mod folder location. It changed nothing.

Mod Manager Version: 0.65.2.0
[TraceLog20180602131050.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2065335/TraceLog20180602131050.txt)

Freshly installed NMM and installed it on an external drive.

I was having a login bug earlier, and decided to do a fresh install of NMM, as I hadn't used it in a while.

**Comment by squid-box** [comment] 2018-06-09 07:45
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:45 UTC
Labels: duplicate
