### ISSUE TITLE
Download progress stops with no error message, eventually reports incomplete

### ISSUE THREAD

**Issue by Herzegovina** [Nexus-Mods/Nexus-Mod-Manager#37] opened 2017-01-31 15:06 UTC
I am using NMM 0.63.13 with Windows 10 Pro 64 bit, managing mods for Fallout 4.

When downloading a mod file, the download will stop progressing for no apparent reason. Both progress and download ETA stop updating. No error message is given. If I don't do anything the download eventually stops and reports it is incomplete; I can restart the download, but the problem will continue. Pausing and then resuming the download causes it to continue normally for a short time before halting again. By doing this repeatedly it is possible to fully download files which appear to work fine. The exact amount of time before it stops varies from almost instant to as long as a minute.

**Comment by Houbsky** [comment] 2017-01-31 17:40
I got the same problem. I've been looking everywhere to find the solution and nothing can be found. Everything is up to date, internet is working correctly on the other sites. Additionally if I try to download mods manually the same s*** happens, mod is downloading and then stops for some reason. Please, help me solve this thing

**Comment by peltonmonster17** [comment] 2017-02-01 19:35
Same here. It' definitely not my internet because other downloads work fine, it's just from nexus.

**Comment by Spectorns6** [comment] 2017-02-03 01:28
I am having the same issue, even when I try to download through windows and manually install the mod.

**Comment by lobo3222** [comment] 2017-02-03 08:01
hi i'm using nmm 0.63.13 (skyrim) ran into the same issue as others on the obis page http://www.nexusmods.com/skyrimspecialedition/mods/4145/?

nmm won't download the main file ends up getting error and nothing is listed in the size or speed during the time it says dowloading
 Error: http://filedelivery.nexusmods.com/1704/OBIS Special Edition-4145-1-05.7z?fid=16421&ttl=1486123127&ri=8192&rs=8192&setec=afc3d2e904482de5b1a5f68b5dd83c47 , unable to finish the download.    
trying to figure out what the issue is any help would be appreciated.

note: i can download other large file mods without issue but not obis, i also noticed that nmm doesn't have the new version listed for obis as well (could that be the overall issue?)

as i said any help would be appreciated thank you. oh and manual downloads fine.

**Comment by Bbone1985** [comment] 2017-02-20 18:37
My MM will not Download the file I need help with it thank you

**Comment by LavCorps** [comment] 2017-03-26 19:13
Try using [0.61.21](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.61.21). It worked for me.

**Comment by squid-box** [comment] 2018-05-24 22:39
If you're not able to download either manually or through NMM, it's likely an issue with your connection.

If anyone of you is still having problems downloading, please try it with the latest NMM.

Then please add a link to the mod you're trying to download and a tracelog (run NMM in Trace Mode (there's a shortcut in the start menu), attempt the download, and then grab the file from your Documents folder, under Nexus Mod Manager).

**Comment by squid-box** [comment] 2018-05-31 12:12
With no reply in a week, I'm closing this issue.

**Closed as completed by squid-box** 2018-05-31 12:12 UTC
Labels: need info

**Comment by Spectorns6** [comment] 2018-05-31 13:48
I submitted this at least a year ago, if not more. Thanks for the response though.

Sent from my HTC

----- Reply message -----

**Comment by squid-box** [comment] 2018-05-31 14:21
If you do still experience this, either re-open this issue or create a new one and provide as much info as you can.

I'm just doing a push trying to clean up old outdated issues, so that anyone that has time to solve problems can do so without having to chase info :)
