### ISSUE TITLE
trace log error

### ISSUE THREAD

**Issue by potyr8992** [Nexus-Mods/Nexus-Mod-Manager#514] opened 2018-07-21 06:09 UTC
Hello, I have a big problem.
As soon as I launch Nexus, I have a trace log error.
What can I do to not have any more.
Here is the last log trace i had:
Trace file has been created: TraceLog20180721072143.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: E:\0skyrporn\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Skyrim: Supported
Determining Game Mode: (From Selection Form) Skyrim
Game Mode Factory Selected: Skyrim (Skyrim)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim (Skyrim)
    Installation Path: E:\0skyrporn\TheElderScrVSkyrLegendary.part1\The Elder Scrolls V Skyrim - Legendary Edition\The Elder Scrolls V Skyrim - Legendary Edition
    Install Info Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info
    Mod Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    Mod Cache Path: E:\Games\Nexus Mod Manager\Skyrim\Mods\cache
    Mod Download Cache: E:\Games\Nexus Mod Manager\Skyrim\Mods\downloads
    Overwrite Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info\overwrites
    Virtual Install Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: E:\0skyrporn\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: E:\0skyrporn\Nexus Mod Manager\GameModes
            Checking: Skyrim.CSharpScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.CSharpScript.SkyrimCSharpScriptType
            Checking: Skyrim.XmlScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.XmlScript.SkyrimXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: E:\0skyrporn\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Running Threads (1)
    3 () 
        Aborted
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	La méthode 'GetFileStream' du type 'Nexus.Client.Mods.Formats.FOMod.FOMod' de l'assembly 'FOMod, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null' n'a pas d'implémentation.
Full Trace: 
	System.TypeLoadException: La méthode 'GetFileStream' du type 'Nexus.Client.Mods.Formats.FOMod.FOMod' de l'assembly 'FOMod, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null' n'a pas d'implémentation.
   à System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   à System.Reflection.RuntimeAssembly.GetExportedTypes()
   à Nexus.Client.Mods.ModFormatRegistry.DiscoverFormats(IModCacheManager p_mcmModCacheManager, List`1 p_lstSupportedFormats, IScriptTypeRegistry p_stgScriptTypeRegistry, String p_strSearchPath)
   à Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   à Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   à Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   à Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   à Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

If you can help me, please help.

**Comment by potyr8992** [comment] 2018-07-21 06:18
should i install vortex?

**Comment by squid-box** [comment] 2018-07-21 07:15
Much like #509, it looks like some files are missing from your installation.

Try reinstalling NMM, and make sure your antivirus isn't blocking any files.

**Comment by potyr8992** [comment] 2018-07-21 10:49
i think it's a yes

**Comment by potyr8992** [comment] 2018-07-21 10:50
ok thank i will try

**Comment by potyr8992** [comment] 2018-07-21 10:55
Thanks for helping me.
It was great.

**Comment by potyr8992** [comment] 2018-07-21 11:44
I have another one:
Trace file has been created: TraceLog20180721134123.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: E:\0skyrporn\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load E:\0skyrporn\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6310.19282, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Skyrim: Supported
Determining Game Mode: (Requested Mode: skyrim) skyrim
Game Mode Factory Selected: Skyrim (Skyrim)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Skyrim (Skyrim)
    Installation Path: E:\0skyrporn\TheElderScrVSkyrLegendary.part1\The Elder Scrolls V Skyrim - Legendary Edition\The Elder Scrolls V Skyrim - Legendary Edition
    Install Info Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info
    Mod Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    Mod Cache Path: E:\Games\Nexus Mod Manager\Skyrim\Mods\cache
    Mod Download Cache: E:\Games\Nexus Mod Manager\Skyrim\Mods\downloads
    Overwrite Path: E:\Games\Nexus Mod Manager\Skyrim\Install Info\overwrites
    Virtual Install Path: E:\Games\Nexus Mod Manager\Skyrim\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: E:\0skyrporn\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: E:\0skyrporn\Nexus Mod Manager\GameModes
            Checking: Skyrim.CSharpScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.CSharpScript.SkyrimCSharpScriptType
            Checking: Skyrim.XmlScript.dll
                Initializing: Nexus.Client.Games.Skyrim.Scripting.XmlScript.SkyrimXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: E:\0skyrporn\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Running Threads (1)
    3 () 
        Aborted
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	La méthode 'GetFileStream' du type 'Nexus.Client.Mods.Formats.FOMod.FOMod' de l'assembly 'FOMod, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null' n'a pas d'implémentation.
Full Trace: 
	System.TypeLoadException: La méthode 'GetFileStream' du type 'Nexus.Client.Mods.Formats.FOMod.FOMod' de l'assembly 'FOMod, Version=1.1.6310.19283, Culture=neutral, PublicKeyToken=null' n'a pas d'implémentation.
   à System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   à System.Reflection.RuntimeAssembly.GetExportedTypes()
   à Nexus.Client.Mods.ModFormatRegistry.DiscoverFormats(IModCacheManager p_mcmModCacheManager, List`1 p_lstSupportedFormats, IScriptTypeRegistry p_stgScriptTypeRegistry, String p_strSearchPath)
   à Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   à Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   à Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   à Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   à Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by squid-box** [comment] 2018-07-21 12:15
It's pretty much the same error, NMM is still missing .dll's. If you already did reinstall it, then it seems something is blocking/removing some files.

**Comment by potyr8992** [comment] 2018-07-21 12:18
but my anti-virus is disabled.
What could be blocked?

**Comment by potyr8992** [comment] 2018-07-21 13:01
o

**Comment by potyr8992** [comment] 2018-07-21 14:59
Please

**Comment by potyr8992** [comment] 2018-07-21 15:31
would be windows?

**Comment by potyr8992** [comment] 2018-07-21 15:32
would be windows?

**Comment by potyr8992** [comment] 2018-07-21 15:49
allo?

**Comment by squid-box** [comment] 2021-03-07 21:18
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:18 UTC
Labels: installation
