### ISSUE TITLE
Nexus Crashes after checking the box "Add shell extensions for supported file types"

### ISSUE THREAD

**Issue by NoxianGray** [Nexus-Mods/Nexus-Mod-Manager#400] opened 2018-06-12 03:37 UTC
**Describe the bug**
I tried installing SkyUI for The Elder Scrolls V and I kept receiving the error 'an exception occurred in the script'. So I went looking for a solution and found a fix that involved checking the box "Add shell extensions for supported file types" in NMM's settings. I could run NMM as an administrator and I could check said box but upon clicking the 'ok' button to close and finalise the settings, NMM crashes. *tracelog has been attached. 

[TraceLog20180612112500.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2092443/TraceLog20180612112500.txt)

**Environment**
- NMM version: 0.65.2
- Mod(s) used: https://www.nexusmods.com/skyrim/mods/3863
                        https://www.nexusmods.com/skyrim/mods/53689
                        https://www.nexusmods.com/skyrim/mods/52019
                        https://www.nexusmods.com/skyrim/mods/43773
                        https://www.nexusmods.com/skyrim/mods/55555/
                        https://www.nexusmods.com/skyrim/mods/30250
                        https://www.nexusmods.com/skyrim/mods/88687
                        https://www.nexusmods.com/skyrim/mods/36006/

Thank You.

**Comment by squid-box** [comment] 2018-06-13 21:38
This is a duplicate of #343, so I'm closing this issue as a duplicate.
Please keep an eye on #343 for any fix for this.

**Closed as completed by squid-box** 2018-06-13 21:38 UTC
Labels: duplicate
