### ISSUE TITLE
the mod manager keeps disabling mods 

### ISSUE THREAD

**Issue by blackknight219** [Nexus-Mods/Nexus-Mod-Manager#112] opened 2017-06-17 21:56 UTC
on the mod manager i enabled a mod i play the game and my mod isnt working i exit off game then i looked into the mod manager and its diabled and i dont get why its doing this

**Comment by Nubbie** [comment] 2019-05-24 16:54
Duplicate of #111 ?

**Closed as completed** 2021-03-08 12:06 UTC
Labels: duplicate
