### ISSUE TITLE
Nexus mod manager crashes on startup

### ISSUE THREAD

**Issue by ComputerSaqtNein** [Nexus-Mods/Nexus-Mod-Manager#851] opened 2019-06-22 10:33 UTC
"Nexus Mod Manager has encountered an error and needs to close."

`Trace file has been created: TraceLog20190622123306.txt
Mod Manager Version: 0.65.11.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\SSD Spiele\Steam Games\steamapps\common\NMM\GameModes
    Checking: Antlr3.Runtime.dll
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: CSharpScript.dll
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Enderal.dll
        Initializing: Nexus.Client.Games.Enderal.EnderalGameModeFactory
    Checking: Fallout3.CSharpScript.dll
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	Die Methode "Parse" im Typ "Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser" der Assembly "Fallout3.XmlScript, Version=0.65.11.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
Full Trace: 
	System.TypeLoadException: Die Methode "Parse" im Typ "Nexus.Client.ModManagement.Scripting.XmlScript.CPL.FO3CplParser" der Assembly "Fallout3.XmlScript, Version=0.65.11.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
   bei System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   bei System.Reflection.RuntimeAssembly.GetExportedTypes()
   bei Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes(EnvironmentInfo p_eifEnvironmentInfo)
   bei Nexus.Client.Bootstrapper.RunMainForm(String[] args)
   bei Nexus.Client.Program.Main(String[] p_strArgs)

        Running Threads (0)
`

**Environment**
- NMM version: _0.7.8_ and older (basically any version I try now)

**Comment by viper1s** [comment] 2019-06-22 12:28
Just had my first crash on startup .
Skyrim SE

**Comment by squid-box** [comment] 2019-06-22 13:35
This is a duplicate of #728, there's a work-around there (clean install).

**Closed as completed** 2021-03-08 00:37 UTC
