### ISSUE TITLE
Deleting a mod doesn't actually delete it

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/Nexus-Mod-Manager#23] opened 2017-01-06 20:19 UTC
I just deleted a mod from NMM, but its files didn't get deleted from disk. No errors or warnings anywhere to be found.

NMM is at 0.63.11
Game in question is Fallout 4 1.8.7 from Steam.
Mods in question are LooksMirror and LooksMenu. But I suspect these are irrelevant.

**Comment by thany** [comment] 2017-01-06 21:04
Possibly related: this also goes for installing a mod, where the main file are (usually-ish) installed properly, but any auxiliary files are skipped. Any directories where auxiliary files should go, are created but left empty.

A good example to test this with, is the "Scrap Everything" mod (select ultimate edition).

**Comment by ousnius** [comment] 2017-01-07 07:57
I've never had this happen to myself ever, but there's the occasional user of BodySlide who doesn't get his full mod installed properly (.exe file would be there but most of the rest missing).

**Comment by thany** [comment] 2017-01-09 09:24
Well, good that it doesn't happen for you. But maybe a better approach is to display error messages on copying over mod files. I'm sure something goes wrong for me, but I have no way of knowing what exactly, as long as NMM is totally silent about it.

**Comment by ousnius** [comment] 2017-01-09 10:27
I'm not a developer of NMM. There are a ton of errors like these, and they're most likely not gonna get fixed since they're working on a new manager.

**Comment by squid-box** [comment] 2018-05-24 22:59
@thany: I'm not seeing this with (tested this issue alongside #4) in NMM 0.65.5 - are you still having these issues? 

If so can you run through the steps to reproduce this problem with NMM in "Trace Mode" (there's a shortcut for it in the start menu), and attach the TraceLog file which will be saved in `%USERPROFILE%\Documents\Nexus Mod Manager\`?

**Comment by thany** [comment] 2018-05-25 10:21
I'm not sure which version I have, but I'm not seeing this anymore atm. I haven't juggled many mods around lately, but the few small ones I removed seemed to have been removed correctly.

**Comment by squid-box** [comment] 2018-05-25 11:50
Thanks for replying, without a way to reproduce it, and after this long, I'm going to close this issue.

Feel free to open a new but report if you encounter it again!

**Closed as completed by squid-box** 2018-05-25 11:50 UTC
