### ISSUE TITLE
Unable to Change "Add Shell Extensions" Setting

### ISSUE THREAD

**Issue by jorgeman72** [Nexus-Mods/Nexus-Mod-Manager#375] opened 2018-06-06 01:47 UTC
Hello all,

I recently downloaded NMM and I'm trying to set up mods for Betheseda's classic hit, Skyrim. After downloading NMM and moving my Skyrim folder outside of its default location (So its acessible by NMM), I tried to download the mod SkyUI (I have SKSE installed). Unfortunately, I get a System.Security.SecurityException error. To fix this, I attempted to change the "Add Shell Extensions..." setting by running as an admin and ticking the box on. When I attempted that, I got the attatched tracelog error ("The specified path is invalid")

If anyone knows how to fix this I would be very apreciative.

[TraceLog20180605213858.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2074516/TraceLog20180605213858.txt)

**Comment by squid-box** [comment] 2018-06-13 21:36
The SecurityException sounds like NMM is run as a user that doesn't have access to either the folder where mods are stored, or where they are installed. If you can attach a TraceLog from that error happening maybe I can help you better.

The Shell Extensions part is a duplicate of #343.

**Comment by squid-box** [comment] 2019-02-15 13:18
With no reply in over 6 months, I'm closing this due to inactivity.

**Closed as completed by squid-box** 2019-02-15 13:18 UTC
Labels: duplicate
