### ISSUE TITLE
NMM launcher crash whan start program

### ISSUE THREAD

**Issue by rekvuem** [Nexus-Mods/Nexus-Mod-Manager#485] opened 2018-07-11 00:07 UTC
After install mods and restart MNN have this bug

Windows 10
Net 4.5
no Antivirus programs

[TraceLog20180711030058.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2182507/TraceLog20180711030058.txt)

**Comment by squid-box** [comment] 2018-07-11 03:56
Duplicate of #300.

**Closed as completed by squid-box** 2018-07-11 03:56 UTC
Labels: duplicate
