### ISSUE TITLE
The process cannot access the file, HELP!!

### ISSUE THREAD

**Issue by kryc3k** [Nexus-Mods/Nexus-Mod-Manager#464] opened 2018-07-06 19:12 UTC
I just downloaded NMM version 0.65.2, and whenever I try to select the game I want to manage (which in this case is fallout 4) or whenever I try to launch the FO4 Mod manager, it either just stop the tasks or it gives me some errors saying that some files couldn't be opened and the tracelog.

**And this is the trace log below**

Trace file has been created: TraceLog20180706194138.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: D:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load D:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading Fallout4: Supported
    Loading FalloutNV: Supported
Determining Game Mode: (From Selection Form) 
Tracing an Unhandled Exception:
Exception: 
Message: 
	The process cannot access the file 'C:\Users\krycek\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_mxjirezo5ovuvygsevop050b2yfmxyzo\0.65.2.0\yovi50s0.newcfg' because it is being used by another process.
Full Trace: 
	System.IO.IOException: The process cannot access the file 'C:\Users\krycek\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_mxjirezo5ovuvygsevop050b2yfmxyzo\0.65.2.0\yovi50s0.newcfg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetCreationTimeUtc(String path, DateTime creationTimeUtc)
   at System.Configuration.Internal.WriteFileContext.DuplicateFileAttributes(String source, String destination)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.StaticWriteCompleted(String streamName, Boolean success, Object writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at Nexus.Client.GameModeSelectionForm.StartupGameMode()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by dyslexicanaboko** [comment] 2018-07-06 19:46
Not trying to be funny, but have you tried restarting your machine? This typically happens when a process is still running and it is in use. In other words if you are running the game while trying to use the mod manager I would not be surprised if this happened. If yes, stop the game, wait like 2 minutes and then try the mod manager again. If it persists restart your machine. If after restarting it is still happening it could be a bug.

**Comment by squid-box** [comment] 2018-07-06 19:52
Duplicate of #389.

**Comment by kryc3k** [comment] 2018-07-06 20:04
yep done that about 5 time already and still didn't work, i even deleted everything nexus related and re-downloaded it

**Comment by squid-box** [comment] 2018-07-10 19:12
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't help, please let us know in #389.

**Closed as completed by squid-box** 2018-07-10 19:12 UTC
Labels: duplicate
