### ISSUE TITLE
error and can't do anything 

### ISSUE THREAD

**Issue by kchicken666** [Nexus-Mods/Nexus-Mod-Manager#650] opened 2018-10-22 15:06 UTC
**Describe the bug** 
So yesterday it was working perfectly fine then I went to get a mod for fallout 4 and then it just started coming up with an error message whenever i try to open it if its from my desktop or from the website when i click download with manager and i have tried everything i have found on the internet about it

**Environment**
- NMM version: 0.65.2
-Mods: it does it if i try and do anything with any mods

![ggggggggggg](https://user-images.githubusercontent.com/44352410/47300423-a8b73a80-d5d9-11e8-9f94-2609855e508a.PNG)
[TraceLog20181022085549.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2501927/TraceLog20181022085549.txt)

**To Reproduce**
I do not know how to reproduce this

**Comment by squid-box** [comment] 2018-10-22 16:46
This is a duplicate of #300, there are some suggestions there.

**Closed as completed** 2019-02-15 17:27 UTC
Labels: duplicate
