### ISSUE TITLE
cannot open mod manager at all

### ISSUE THREAD

**Issue by jagdthetiger** [Nexus-Mods/Nexus-Mod-Manager#714] opened 2019-04-08 19:36 UTC
tried installing mods, got a trace issue, suddenly stopped working and no wont open without reporting a trace issue
[TraceLog20190408203218.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3055982/TraceLog20190408203218.txt)

**Comment by squid-box** [comment] 2019-04-08 20:04
This is a duplicate of #300, look there for a solution to this issue.

**Closed as completed by squid-box** 2019-04-08 20:04 UTC
Labels: duplicate
