### ISSUE TITLE
Crash after game selection screen

### ISSUE THREAD

**Issue by Ealind** [Nexus-Mods/Nexus-Mod-Manager#381] opened 2018-06-07 12:14 UTC
I get an error message saying Nexus Mod Manager has encountered an error and needs to close.  I am attaching the tracelog.

I open the game in administrator mode and have used it only once.  The only mods I am using are for Skyrim Special Edition (which I have), but putting them in the folders for Skyrim VR.

Thanks for any help you can give.

Trace file has been created: TraceLog20180607080949.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading SkyrimSE: Supported
Determining Game Mode: (From Selection Form) 
Tracing an Unhandled Exception:
Exception: 
Message: 
	Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden. (C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config)
Full Trace: 
	System.Configuration.ConfigurationErrorsException: Failed to save settings: An error occurred loading a configuration file: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden. (C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config) ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden. (C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at Nexus.Client.GameModeSelectionForm.StartupGameMode()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Inner Exception:
System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden. (C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config) ---> System.IO.IOException: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   --- End of inner exception stack trace ---
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
Inner Exception:
System.IO.IOException: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing because it is read-only or hidden.
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext, Boolean assertPermissions)
   at System.Configuration.ClientSettingsStore.ClientSettingsConfigurationHost.OpenStreamForWrite(String streamName, String templateStreamName, Object& writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)

**Comment by squid-box** [comment] 2018-06-09 07:41
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:41 UTC
Labels: duplicate

**Comment by neoh4x0r** [comment] 2018-06-09 08:27
@Ealind 
@squid-box 

An important part the error log:
System.IO.IOException: Unable to open file 'C:\Users\Allan\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_2eir2d35cqbpwgw1etv4i5pyvaneja0r\0.65.2.0\user.config' for writing **because it is read-only or hidden**.

The read-only and/or hidden attributes should be cleared.

**Comment by squid-box** [comment] 2018-06-09 08:32
So that's likely not the problem, that file is handled entirely by C#'s Settings implementation. From what I'm seeing it looks like NMM is blasting Settings.Save() multiple times randomly, eg. when the UI resizes itself.

The problem seems to be that the file is actually in use when this happens.
