### ISSUE TITLE
"Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down."

### ISSUE THREAD

**Issue by amberdunn11** [Nexus-Mods/Nexus-Mod-Manager#240] opened 2018-02-05 05:59 UTC
Whenever I try to login, it gives me this error "Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down." I can however, log in on the website and my firewall is not blocking

**Comment by Arefu** [comment] 2018-02-05 07:55
Duplicate of #237

**Comment by squid-box** [comment] 2018-05-24 19:13
Given the age of this issue and the fact there's a more fleshed out one (#237), I'm closing this issue.

Please see other issue for some helpful tips.

**Closed as completed by squid-box** 2018-05-24 19:13 UTC
Labels: duplicate, login
