### ISSUE TITLE
NMM 63.13 falsely installing some mods.

### ISSUE THREAD

**Issue by Cylek358** [Nexus-Mods/Nexus-Mod-Manager#52] opened 2017-03-18 19:09 UTC
I've recently went back to NMM to use with Skyrim Special Edition, and have found that some mods won't properly install.  They will show as installed, but the files are not in the directory nor have any effect ingame.  On restarting the client, the mods will once again show as disabled, and enabling them again does nothing save make it look activated.  This issue seems most common with Texture mods that don't use ESP files, as they are simple replacers, as well as plugin mods that only add a dll file.

**Comment by Ghostwalker71** [comment] 2017-03-21 16:05
Many DLL mods must be installed manually because the file must be placed in the root game directory instead of the data folder.
The texture mods very likely have several options placed in different folders and if the creator didn't make a fomod to process the install then it is likely the texture are in the data folder but stuck in subfolders that are of no use to the game. the only way to fix this is to either install manually or create a fomod installer. neither option is very good for texture mods.
You can verify if this is the issue by unpacking the mod files and reviewing the folder structure.

**Comment by squid-box** [comment] 2021-03-07 11:04
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.

**Closed as completed** 2021-03-07 11:04 UTC
