### ISSUE TITLE
NMM doesn't start up

### ISSUE THREAD

**Issue by SargentSucc** [Nexus-Mods/Nexus-Mod-Manager#585] opened 2018-08-29 20:36 UTC
When I open up nexus it shows a crash report saying Nexus mod manager has encountered an error and needs to close. A trace log has been created at:(my info)

[TraceLog20180829163621.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2333712/TraceLog20180829163621.txt)

**Comment by squid-box** [comment] 2018-08-29 21:13
Duplicate of #389, download the latest version from GitHub and this should be solved.

https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Closed as completed** 2019-02-15 17:29 UTC
Labels: duplicate
