### ISSUE TITLE
Bug report nmm v0.65.2.0 ''value cannot be null'' message

### ISSUE THREAD

**Issue by SolidusBlindSnake** [Nexus-Mods/Nexus-Mod-Manager#300] opened 2018-05-10 06:53 UTC
================================================================
Thanks to Paul McGoldrick for pointing out what the problem was caused by and the first solution/workaround so far to this issue; NMM can't find the fallout4.exe executable as such it comes up null, so the solution would be in this case to revert the name back to fallout4.exe for those like myself that renamed it to fallout4launcher.exe so as to be able to open the game or as Paul suggested, name the fallout4vr.exe to fallout4.exe for those that have it.

This however will still leave you with the issue of not being able to open your game even through/with f4se.exe or f4 config tool.
**UPDATE:** Thanks AeroMerchant for confirming this also works for the VR version of FO4!
**UPDATE2** Thanks JimmyRJump from the Nexusmods forums for this: 
> Copy the game's exe to anywhere, rename it and put it back.  Tadàààà: two exe's, one original and one renamed.

This will alow NMM to open without issues and having the copy renamed to fallout4launcher.exe won't conflict there and will as such allow for a functional launcher for the game to open but still no solution to the f4se not working.

================================================================

[TraceLog20180510021011.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1990586/TraceLog20180510021011.txt)

So before updating to this version I was using nmm 0.53 if I recall, downloaded and installed the newest version over that one after getting the ''cannot login'' error not allowing me to download mods. Prior to this situation I could run on SSE and FO4 with all DLC's. Now only SSE nmm is functioning and the FO4 nmm gives me the null error. 

Don't know if this is relevant but I have installed the F4 CK, F4 config tool, F4SE, not that I have had luck running the latter that I know of. I am running TOP after using Archive2 to install it, my .esp mods don't remain active, always gotta load 'em in F4 mods tab in main menu before starting game.

I must also mention that my fallout4.exe and fallout4Launcher.exe have both been renamed as after vanilla install on Steam, with vanilla saves, it would CTD on click of ''Play'' without even starting the game and still been vanilla. The fix I found was fallout4.exe renamed to Fallout4Launcher.exe and Fallout4Launcher.exe to whatever, in this case Fallout4Launcher1.exe

I have not tried uninstalling nmm in fear of losing my mod files and damaging my games.

**Comment by JaydenWindsong** [comment] 2018-05-10 18:16
I am also receiving this error.  Have tried uninstalling and then reinstalling, does not fix the problem.  Attached is trace log.
[TraceLog20180510111408.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1992780/TraceLog20180510111408.txt)

**Comment by suburbannun** [comment] 2018-05-11 18:29
Same thing here, but only when trying to open it for Fallout 4 (VR).
Worked fine until today.Tried three different versions an got the same message.
[TraceLog20180511202819.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/1996433/TraceLog20180511202819.txt)

**Comment by paulmcgoldrick** [comment] 2018-05-11 21:30
Seems like the issue is here:
https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/GamebryoBase/GamebryoGameModeBase.cs#L52

There is no `Fallout4.exe` executable, and so returning `null` here, later it tries to do a version comparison against this GameMode.GameVersion, and it seems like this is causing the trace (here https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/GamebryoBase/PluginManagement/LoadOrderManager/PluginOrderManager.cs#L288 )

I was able to work around this issue by copying Fallout4VR.exe to Fallout4.exe

**Comment by SolidusBlindSnake** [comment] 2018-05-11 23:26
JaydenWindsong did that mess your NMM mod list or anything else for that matter? 

paulmvgoldrick any idea how one could work around this if you don't have the vr.exe and if keeping the fallout4.exe as is just won't load the game... oh god am I gonna have to rename every single time my files to open nmm and fallout respectively! :O

**Comment by SolidusBlindSnake** [comment] 2018-05-11 23:28
suburbannun 3 versions of what exactly? Fallout? NMM?

**Comment by SolidusBlindSnake** [comment] 2018-05-12 00:41
So I tried renaming my original fallout4.exe file back to that name rather then having it take the fallout4launcher.exe and it does stop the null error. So that's the null error solution. 

However this still leaves me with the issue that my fallout game won't open it CTD's on start if the fallout4.exe isn't named fallout4launcher, which was the most effective and simplest solution I'd found to this very obnoxious problem which is also making me have other problems i'm sure... Any advice, tips, etc, etc?

Edit: Possible solution: after renaming it back to fallout4.exe and being able to access F04 NMM maybe add a command/argument in settings to ignore the .exe name and use whichever name it is works for the user? If anybody knows what  that would look like, the info would be appreciated as I can't f****** run fallout4 without a different fallout.exe name on steam...

**Comment by suburbannun** [comment] 2018-05-12 11:53
> suburbannun 3 versions of what exactly? Fallout? NMM?

SolidusBlindSnake, sorry my bad. Three versions of NMM.
Added Fallout4.exe to Fallout 4VR folder, it's all good now.

Thanks a lot!!
: )

**Comment by AeroMerchant** [comment] 2018-05-17 23:28
Worked perfectly thank you was modding vr :) now back to browsing the mods.

**Comment by SolidusBlindSnake** [comment] 2018-06-03 04:55
bumpity bump! Still strugling with this, help please somebody! I have since also tried sorting my mod list with LOOT to no avail. Checked cache integrity multiple times, mostly seems to reacquire the fo4 executables judging from 1.4mb size of downloads and it changes nothing. I'm also now not able to run other steam games....

**Comment by squid-box** [comment] 2018-07-10 20:11
So with #429 being merged and available from 0.65.7 and onwards, I'm closing this issue.
The fix is to simply go back to the game selection window, as NMM can't do anything to handle users renaming or moving critical files.

**Closed as completed by squid-box** 2018-07-10 20:11 UTC

**Comment by mkreilis** [comment] 2018-09-09 21:35
The links from paulmcgoldrick's comment are 404's. Or maybe I'm just not understanding the fix here.

**Comment by squid-box** [comment] 2018-09-09 21:42
The issue is that your Fallout4.exe doesn't contain information needed, which only happens if it has been replaced/patched/cracked. 

Restore your Fallout 4 installation and it will work again

**Comment by Alkaris** [comment] 2018-11-08 07:49
Seems I'm having this very issue.

```
Trace file has been created: TraceLog20181108181226.txt
Mod Manager Version: 0.65.10.0(mono)
OS version: Microsoft Windows NT 6.1.7601.65536 Service Pack 1
Installed .NET Versions:
	v1.1.4322 SP 1
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.5: 4.5 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        
        Tracing an Unhandled Exception:
        Exception: 
Message: 
	The classes in the module cannot be loaded.
Full Trace: 
	System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetExportedTypes () [0x00000] in <773ec02b42f74a918ccd74911c8063c9>:0 
  at Nexus.Client.Games.GameModeRegistry.DiscoverSupportedGameModes (Nexus.Client.EnvironmentInfo p_eifEnvironmentInfo) [0x000a1] in <bf7fc43be1914ee19c8a724de75ce53d>:0 
  at Nexus.Client.Bootstrapper.GetSupportedGameModes () [0x00000] in <bf7fc43be1914ee19c8a724de75ce53d>:0 
  at Nexus.Client.Bootstrapper.RunMainForm (System.String[] args) [0x000a9] in <bf7fc43be1914ee19c8a724de75ce53d>:0 
  at Nexus.Client.Program.Main (System.String[] p_strArgs) [0x0015b] in <bf7fc43be1914ee19c8a724de75ce53d>:0 

        Running Threads (0)
```

**Comment by squid-box** [comment] 2018-11-08 08:07
No, you aren't. You're having problems loading NMM's dll's, likely due to using Mono.
