### ISSUE TITLE
Crash after game selection

### ISSUE THREAD

**Issue by Bregoran** [Nexus-Mods/Nexus-Mod-Manager#468] opened 2018-07-07 18:43 UTC
- NMM version: 0.65.7

I made a new Clean installation of Fallout 4 today, started the game one time and then started installing some mods till [Perk Magazine Material Fix](https://www.nexusmods.com/fallout4/mods/6906?tab=description) got an error while installation. I restarted the NMM and it started to crash. Then I tried to a clean reinstall (uninstall, clean registry, reboot, clean registry, reboot, new installation) and the NMM always crashes after selecting a game and asking for the [NMM path](https://imgur.com/abE0x7i).

One point i only realized now is, I got a new hard drive (M:) and after clean installation of Fallout 4 the NMM still used my old hard drive (D:) as virtual installation drive without asking me if I wanted it to change it, after many NMM crashes, I tried to move the virtual folder to (M:) but it still crashed.

I have only Witcher 3 besides Fallout 4 installed and it crashes too.

Fallout 4 Selected [TraceLog20180707203541.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2172999/TraceLog20180707203541.txt)
Witcher 3 Selected [TraceLog20180707203214.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2172996/TraceLog20180707203214.txt)

**Comment by squid-box** [comment] 2018-07-09 08:08
Duplicate of #465.

**Closed as completed** 2018-08-15 10:39 UTC
Labels: duplicate
