### ISSUE TITLE
Nexus Mod Manager has encountered an error and needs to close

### ISSUE THREAD

**Issue by ILDization** [Nexus-Mods/Nexus-Mod-Manager#765] opened 2019-05-15 07:06 UTC
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Nexus Mod Manager has encountered an error and needs to close

[TraceLog20190515030926.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3181294/TraceLog20190515030926.txt)

**Environment**
- NMM version: _0.70.3

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by jbostrus** [comment] 2019-05-15 07:17
I had someone else on Discord come up with this. We never did figure out exactly what was causing it. Though he did an uninstall of NMM and reinstalled and that resolved it for him. Although he then had to reconfigure NMM to some extent.

Hopefully someone a bit more familiar with the code and procedures could shed light on the subject.

Edit: I see a few other issues opened for this problem. One with some other info is #728

**Comment by squid-box** [comment] 2019-05-15 07:32
Duplicate of #728, it's due to old files not being updated/removed during an update. We're not sure what's going wrong and not everyone gets it.

Workaround is to uninstall NMM, remove any remaining files from the program files directory and install it again. No need to remove configuration files.

**Comment by jbostrus** [comment] 2019-05-15 07:32
Yea I'm not sure why my friend had to reconfigure it. Probably something he messed up.

**Comment by ILDization** [comment] 2019-05-15 07:43
Thanks for the replies, a reinstall without reconfiguration fixed the issue.

**Comment by squid-box** [comment] 2019-05-15 09:09
Closing this issue, #728 will have to handle this.

**Closed as completed by squid-box** 2019-05-15 09:09 UTC
Labels: duplicate
