### ISSUE TITLE
NMM wouldn't accept mods after download and now wont load with encountering error

### ISSUE THREAD

**Issue by Vaultpirate** [Nexus-Mods/Nexus-Mod-Manager#371] opened 2018-06-05 00:09 UTC
_Please give as much information as you can, replace/remove italicized text._

After downloading the mods to the nmm trying to turn them on, some would but others just wouldn't for unknown reason and now wont start without displaying a error message.

- NMM version: _0.65.0_
- Mod(s) used: https://www.nexusmods.com/fallout4/mods/9667
https://www.nexusmods.com/fallout4/mods/15
https://www.nexusmods.com/fallout4/mods/25
https://www.nexusmods.com/fallout4/mods/133
https://www.nexusmods.com/fallout4/mods/359
https://www.nexusmods.com/fallout4/mods/12631
https://www.nexusmods.com/fallout4/mods/21872
https://www.nexusmods.com/fallout4/mods/32039
https://www.nexusmods.com/fallout4/mods/32050
https://www.nexusmods.com/fallout4/mods/13627
https://www.nexusmods.com/fallout4/mods/31965
https://www.nexusmods.com/fallout4/mods/4398
https://www.nexusmods.com/fallout4/mods/11402

Tracelogs
[TraceLog20180604142628.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070341/TraceLog20180604142628.txt)
[TraceLog20180605000427.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070342/TraceLog20180605000427.txt)
[TraceLog20180605000812.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070343/TraceLog20180605000812.txt)
[TraceLog20180605003433.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070344/TraceLog20180605003433.txt)
[TraceLog20180605003857.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070345/TraceLog20180605003857.txt)
[TraceLog20180605005241.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070346/TraceLog20180605005241.txt)
[TraceLog20180605005249.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070347/TraceLog20180605005249.txt)
[TraceLog20180605005414.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070348/TraceLog20180605005414.txt)
[TraceLog20180605005427.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070349/TraceLog20180605005427.txt)
[TraceLog20180605005639.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2070350/TraceLog20180605005639.txt)

**Comment by squid-box** [comment] 2018-06-09 07:45
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:45 UTC
Labels: duplicate
