### ISSUE TITLE
NMM won't load past splash screen

### ISSUE THREAD

**Issue by BigIronV3** [Nexus-Mods/Nexus-Mod-Manager#523] opened 2018-07-24 02:54 UTC
I was uninstalling some NV mods I didn't like and while removing one of them NMM crashed and will no longer load. 
This only happens for NV though.  I can load the F3 and F4 managers just fine with no issues. 
When I load the NV manager, the splash screen will appear, load to about 60%, crash and give me a TraceLog file.  
All help is greatly appreciated 
Here is the TraceLog file: 

Trace file has been created: TraceLog20180723194532.txt
Mod Manager Version: 0.65.2.0
OS version: Microsoft Windows NT 6.2.9200.0
Installed .NET Versions:
	CDF SP 0
	v2.0.50727 SP 2
	v3.0 SP 2
	v3.5 SP 1
	v4 SP 0
	v4.0 SP 0
	v4.5: 4.6 or later
Tracing is forced: False

Discovering Game Mode Factories...
    Looking in: C:\Program Files\Nexus Mod Manager\GameModes
    Checking: BreakingWheel.dll
        Initializing: Nexus.Client.Games.BreakingWheel.BreakingWheelGameModeFactory
    Checking: DarkSouls.dll
        Initializing: Nexus.Client.Games.DarkSouls.DarkSoulsGameModeFactory
    Checking: DarkSouls2.dll
        Initializing: Nexus.Client.Games.DarkSouls2.DarkSouls2GameModeFactory
    Checking: DragonAge.dll
        Initializing: Nexus.Client.Games.DragonAge.DragonAgeGameModeFactory
    Checking: DragonAge2.dll
        Initializing: Nexus.Client.Games.DragonAge2.DragonAge2GameModeFactory
    Checking: DragonsDogma.dll
        Initializing: Nexus.Client.Games.DragonsDogma.DragonsDogmaGameModeFactory
    Checking: Fallout3.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout3.dll
        Initializing: Nexus.Client.Games.Fallout3.Fallout3GameModeFactory
    Checking: Fallout3.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout3.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Fallout4.dll
        Initializing: Nexus.Client.Games.Fallout4.Fallout4GameModeFactory
    Checking: Fallout4.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Fallout4.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: GamebryoBase.dll
    Checking: Grimrock.dll
        Initializing: Nexus.Client.Games.Grimrock.GrimrockGameModeFactory
    Checking: Morrowind.dll
        Initializing: Nexus.Client.Games.Morrowind.MorrowindGameModeFactory
    Checking: NoMansSky.dll
        Initializing: Nexus.Client.Games.NoMansSky.NoMansSkyGameModeFactory
    Checking: Oblivion.dll
        Initializing: Nexus.Client.Games.Oblivion.OblivionGameModeFactory
    Checking: Skyrim.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Skyrim.dll
        Initializing: Nexus.Client.Games.Skyrim.SkyrimGameModeFactory
    Checking: Skyrim.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\Skyrim.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: SkyrimSE.dll
        Initializing: Nexus.Client.Games.SkyrimSE.SkyrimSEGameModeFactory
    Checking: SkyrimSE.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\SkyrimSE.XmlScript.dll: cannot find dependency AntlrUtil, Version=1.1.6689.33167, Culture=neutral, PublicKeyToken=null
    Checking: Starbound.dll
        Initializing: Nexus.Client.Games.Starbound.StarboundGameModeFactory
    Checking: StateOfDecay.dll
        Initializing: Nexus.Client.Games.StateOfDecay.StateOfDecayGameModeFactory
    Checking: TESO.dll
        Initializing: Nexus.Client.Games.TESO.TESOGameModeFactory
    Checking: WarThunder.dll
        Initializing: Nexus.Client.Games.WarThunder.WarThunderGameModeFactory
    Checking: Witcher2.dll
        Initializing: Nexus.Client.Games.Witcher2.Witcher2GameModeFactory
    Checking: Witcher3.dll
        Initializing: Nexus.Client.Games.Witcher3.Witcher3GameModeFactory
    Checking: WorldOfTanks.dll
        Initializing: Nexus.Client.Games.WorldOfTanks.WoTGameModeFactory
    Checking: XCOM2.dll
        Initializing: Nexus.Client.Games.XCOM2.XCOM2GameModeFactory
    Checking: XRebirth.dll
        Initializing: Nexus.Client.Games.XRebirth.XRebirthGameModeFactory
Loading Game Mode Factories for Installed Games...
    Loading FalloutNV: Supported
    Loading Fallout4: Supported
    Loading Fallout3: Supported
Determining Game Mode: (From Selection Form) FalloutNV
Game Mode Factory Selected: Fallout: New Vegas (FalloutNV)
Creating Game Mode mutex (Attempt: 0)
Game Mode Built: Fallout: New Vegas (FalloutNV)
    Installation Path: d:\steam\steamapps\common\Fallout New Vegas
    Install Info Path: d:\Games\Nexus Mod Manager\FalloutNV\Install Info
    Mod Path: D:\Games\Nexus Mod Manager\FalloutNV\Mods
    Mod Cache Path: D:\Games\Nexus Mod Manager\FalloutNV\Mods\cache
    Mod Download Cache: D:\Games\Nexus Mod Manager\FalloutNV\Mods\downloads
    Overwrite Path: d:\Games\Nexus Mod Manager\FalloutNV\Install Info\overwrites
    Virtual Install Path: D:\Games\Nexus Mod Manager\FalloutNV\Mods
    NMM Link Path: 
Scanning for read-only files...
Initializing Mod Repository...
Registering supported Script Types...
    Discovering Script Types...
        Discovering Generic Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\ScriptTypes
            Checking: Antlr3.Runtime.dll
            Checking: AntlrUtil.dll
            Checking: CSharpScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.CSharpScript.CSharpScriptType
            Checking: ModScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.ModScript.ModScriptType
            Checking: XmlScript.dll
                Initializing: Nexus.Client.ModManagement.Scripting.XmlScript.XmlScriptType
        Discovering Game Mode Specific Script Types...
            Looking in: C:\Program Files\Nexus Mod Manager\GameModes
            Checking: FalloutNV.CSharpScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.CSharpScript.FalloutNVCSharpScriptType
            Checking: FalloutNV.XmlScript.dll
                Initializing: Nexus.Client.Games.FalloutNV.Scripting.XmlScript.FalloutNVXmlScriptType
    Found 3 script types.
Registering supported mod formats...
    Discovering Mod Formats...
        Looking in: C:\Program Files\Nexus Mod Manager\ModFormats
        Checking: FOMod.dll
            Initializing: Nexus.Client.Mods.Formats.FOMod.FOModFormat
    Found 1 formats.
Finding managed mods...
    Discovering Managed Mods...
        Looking in: D:\Games\Nexus Mod Manager\FalloutNV\Mods
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\16-9 Ratio Main screen for NMCs Texture Pack-43135.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\ADAM - DATA-43192-4-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Asurah Animation pack-64339-0-2-0c.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Better Pickup Prompt-63091-2-0.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Book of Steel - Compatibility Edition-60666-2-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\BornagainFNVCombatArmor4096-48068-1-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\BornagainFNVCombatArmorLonesomeRoad4096-48068-1-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\CAGE 1.3.9.2-42428-1-9-3-2.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Caravan Pack Weapons Ironsight Fix-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\CASM_NV_1_0_2b-36730-1-0-2b.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Chem N Health Re-Texts for your Enjoyment-61773-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\ChristineCOSRifle-38285-1-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Classic Pack Weapons Ironsight Fix-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Cyrus's Alcohol Pack-61735-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Dead Money DLC weapons ironsight fix-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Decorated BOS Bunker V1.1a-63084-V1-1a.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\DYNAVISION 3 FULL-51577-1-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Elevator-63089-1-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Enhanced Blood Textures-34917-2-22c.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Enhanced Camera-55334-1-4b.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Fallout Character Overhaul 3.0-54460-3-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Fallout Character Overhaul 3.01-54460-3-01.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Fallout_New_Vegas_Interface_Mod_Revelation60-34971-0-60.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Feral Ghould HD-53960-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\FNV Realistic Wasteland Lighting - All DLC-52037-v5-52.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\FOV Slider 2.5-55085-2-5.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Ghoul retexture-49449-1-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\GRA WRP Patch V2-50279-2-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\GRA WRP Unofficial Patch Ironsight Fix-64339-2-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Gun Runners Arsenal weapons ironsight fix-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Honest Hearts DLC weapons ironsight fix-64339-0-2.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\IMPACT - The Michael Bay-57113-2-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\IMPACT-62050-1-1-2.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Improved Heavy Weapons Textures 1.5-56314-1-5.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\JIP LN NVSE Plugin-58277-54-20.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Low Res Textures for Interface Mod - Revelation-47744-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\M14_v1-48477-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\M37 Ithaca v1_1-47457-1-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Main File Beta 7_2-52721-beta.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\MGs NCR Pack 7-42551.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Micalovs Weapon Pack 1_7_2-47393-1-7-2.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Millenia M-14 Patch-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Millenia M37 Ithaca Patch-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Millenia Remington 870 Sawn-Off Patch-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Millenia Weapon Retexture Project Ironsight Fix-64339-1-95.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\New 12_7mm SMG -38285-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\NMCs Textures NV LARGE Pack Part 1 of 3 FOR NMM -43135-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\NMCs Textures NV LARGE Pack Part 2 of 3 FOR NMM -43135-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\NMCs Textures NV LARGE Pack Part 3 of 3 FOR NMM-43135-1-0.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Ojo Bueno Texture Pack for FNV - ULTRA-39755-Quiznak.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\One HUD (oHUD)-44757-1-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Populated Casinos V0_96-35369-V0-96.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Populated Forlorn Hope UPDATED-55246-1-2.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Populated Wasteland v0_3e-36432-1.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Project Nevada 2_5-40040-2-5.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Remington870SawedOff-47255-1-4.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Russell Version 1.17-50107-1-17.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\RWL - Doc Mitchells House Reduced Glare and Shine-52037-v5-5.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\RWL NV - Blur Remover-52037-v5-5.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Sapper Leg Fix-52721-update.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Sit Anywhere-57165-1-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Someguy Series 2 dot 0-48925-2-0.rar
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\The Mod Configuration Menu.fomod
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\The Strip Open V1-4-38056-V1-4.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\UI Compatibility Patches - DarN and Revelation-42483-1-3.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\UIO - User Interface Organizer-57174-1-31.zip
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Vanilla weapon ironsight fix (Non - DLC)-64339-0-1.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Version 12-38844-12.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\Wasteland Flora Overhaul v2dot8a - Fertile Version-39856-2-8a.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\weapon_retexture_project_1dot95-38285-1-95.7z
            Registered.
        Found: D:\Games\Nexus Mod Manager\FalloutNV\Mods\YUP - Base Game and All DLC-51664-11-3.7z
            Registered.
    Found 71 managed mods.
Initializing Install Log...
    Checking if upgrade is required...
    Path: d:\Games\Nexus Mod Manager\FalloutNV\Install Info\InstallLog.xml
    Loaded from XML.
    Found Dummy Mod: ORIGINAL_VALUE...OK
    Found CASM_NV_1_0_2b-36730-1-0-2b.7z...OK
    Found The Mod Configuration Menu.fomod...OK
    Found JIP LN NVSE Plugin-58277-54-20.7z...OK
    Found FOV Slider 2.5-55085-2-5.7z...OK
    Found ADAM - DATA-43192-4-0.rar...OK
    Found Cyrus's Alcohol Pack-61735-1.rar...OK
    Found Better Pickup Prompt-63091-2-0.zip...OK
    Found Book of Steel - Compatibility Edition-60666-2-1-0.7z...OK
    Found BornagainFNVCombatArmor4096-48068-1-0.rar...OK
    Found BornagainFNVCombatArmorLonesomeRoad4096-48068-1-0.rar...OK
    Found CAGE 1.3.9.2-42428-1-9-3-2.7z...OK
    Found Chem N Health Re-Texts for your Enjoyment-61773-1.rar...OK
    Found Elevator-63089-1-0.rar...OK
    Found Decorated BOS Bunker V1.1a-63084-V1-1a.zip...OK
    Found IMPACT - The Michael Bay-57113-2-0.7z...OK
    Found IMPACT-62050-1-1-2.7z...OK
    Found FNV Realistic Wasteland Lighting - All DLC-52037-v5-52.7z...OK
    Found RWL - Doc Mitchells House Reduced Glare and Shine-52037-v5-5.7z...OK
    Found RWL NV - Blur Remover-52037-v5-5.7z...OK
    Found Feral Ghould HD-53960-1-0.7z...OK
    Found MGs NCR Pack 7-42551.7z...OK
    Found Main File Beta 7_2-52721-beta.rar...OK
    Found Sapper Leg Fix-52721-update.rar...OK
    Found NMCs Textures NV LARGE Pack Part 1 of 3 FOR NMM -43135-1-0.7z...OK
    Found The Strip Open V1-4-38056-V1-4.zip...OK
    Found NMCs Textures NV LARGE Pack Part 2 of 3 FOR NMM -43135-1-0.7z...OK
    Found NMCs Textures NV LARGE Pack Part 3 of 3 FOR NMM-43135-1-0.7z...OK
    Found 16-9 Ratio Main screen for NMCs Texture Pack-43135.rar...OK
    Found Populated Casinos V0_96-35369-V0-96.zip...OK
    Found Populated Forlorn Hope UPDATED-55246-1-2.rar...OK
    Found Populated Wasteland v0_3e-36432-1.rar...OK
    Found Wasteland Flora Overhaul v2dot8a - Fertile Version-39856-2-8a.7z...OK
    Found ChristineCOSRifle-38285-1-0.rar...OK
    Found New 12_7mm SMG -38285-1-0.7z...OK
    Found weapon_retexture_project_1dot95-38285-1-95.7z...OK
    Found YUP - Base Game and All DLC-51664-11-3.7z...OK
    Found Ghoul retexture-49449-1-1.rar...OK
    Found Improved Heavy Weapons Textures 1.5-56314-1-5.7z...OK
    Found Project Nevada 2_5-40040-2-5.7z...OK
    Found DYNAVISION 3 FULL-51577-1-1.rar...OK
    Found UIO - User Interface Organizer-57174-1-31.zip...OK
    Found One HUD (oHUD)-44757-1-1.rar...OK
    Found Ojo Bueno Texture Pack for FNV - ULTRA-39755-Quiznak.zip...OK
    Found Enhanced Blood Textures-34917-2-22c.rar...OK
    Found GRA WRP Patch V2-50279-2-1.7z...OK
    Found Fallout Character Overhaul 3.0-54460-3-0.rar...OK
    Found Fallout Character Overhaul 3.01-54460-3-01.rar...OK
    Found M14_v1-48477-1-0.7z...OK
    Found M37 Ithaca v1_1-47457-1-1.7z...OK
    Found Remington870SawedOff-47255-1-4.7z...OK
    Found Sit Anywhere-57165-1-0.rar...OK
    Found Enhanced Camera-55334-1-4b.zip...OK
    Found Micalovs Weapon Pack 1_7_2-47393-1-7-2.7z...OK
    Found Fallout_New_Vegas_Interface_Mod_Revelation60-34971-0-60.rar...OK
    Found Low Res Textures for Interface Mod - Revelation-47744-1-0.7z...OK
    Found UI Compatibility Patches - DarN and Revelation-42483-1-3.7z...OK
    Found Version 12-38844-12.7z...OK
    Found Asurah Animation pack-64339-0-2-0c.7z...OK
    Found Caravan Pack Weapons Ironsight Fix-64339-0-1.7z...OK
    Found Classic Pack Weapons Ironsight Fix-64339-0-1.7z...OK
    Found Dead Money DLC weapons ironsight fix-64339-0-1.7z...OK
    Found GRA WRP Unofficial Patch Ironsight Fix-64339-2-1.7z...OK
    Found Gun Runners Arsenal weapons ironsight fix-64339-0-1.7z...OK
    Found Honest Hearts DLC weapons ironsight fix-64339-0-2.7z...OK
    Found Millenia M-14 Patch-64339-0-1.7z...OK
    Found Millenia M37 Ithaca Patch-64339-0-1.7z...OK
    Found Millenia Remington 870 Sawn-Off Patch-64339-0-1.7z...OK
    Found Millenia Weapon Retexture Project Ironsight Fix-64339-1-95.7z...OK
    Found Vanilla weapon ironsight fix (Non - DLC)-64339-0-1.7z...OK
    Found Russell Version 1.17-50107-1-17.rar...OK
    Found Someguy Series 2 dot 0-48925-2-0.rar...OK
    
    Tracing an Unhandled Exception:
    Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModManagement.InstallationLog.InstallLog.LoadInstallLog()
   at Nexus.Client.ModManagement.InstallationLog.InstallLog..ctor(ModRegistry p_mdrManagedModRegistry, IGameMode p_gmdGameMode, String p_strModInstallDirectory, String p_strLogPath)
   at Nexus.Client.ModManagement.InstallationLog.InstallLog.Initialize(ModRegistry p_mdrManagedModRegistry, IGameMode p_gmdGameMode, String p_strModInstallDirectory, String p_strLogPath)
   at Nexus.Client.ApplicationInitializer.InitializeServices(IGameMode p_gmdGameMode, IModRepository p_mrpModRepository, NexusFileUtil p_nfuFileUtility, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoApplicationInitialize(IGameModeFactory p_gmfGameModeFactory, SynchronizationContext p_scxUIContext, ViewMessage& p_vwmErrorMessage)
   at Nexus.Client.ApplicationInitializer.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

    Running Threads (1)
    3 () 
        Aborted

**Comment by squid-box** [comment] 2021-03-07 21:18
It looks like the install log for your NV setup is gone/broken. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:18 UTC
