### ISSUE TITLE
Open URL:Nexus Mod and doest not download the mod 

### ISSUE THREAD

**Issue by POLKIOTMH** [Nexus-Mods/Nexus-Mod-Manager#239] opened 2018-01-30 20:22 UTC
when I click download with managers with chrome it open a little thing on the top says OPEN URL:NEXUS MOD and when I click on that the mod doesn't download with the application open

**Comment by Nubbie** [comment] 2019-05-26 13:41
@squid-box Duplicate of #132

**Comment by squid-box** [comment] 2021-03-07 21:04
This is likely just a problem with the nxm url association. As there have been changes to how we set that up since this was reported, I'm closing this issue as outdated.

If it's still an ongoing issue, please create a new issue with relevant information like version used and preferably a TraceLog you've gotten generated when trying to associate NMM with nxm urls.

Sorry for the inconvenience.

**Closed as completed by squid-box** 2021-03-07 21:04 UTC
