### ISSUE TITLE
Idk y its doing this and i cant fix it seems

### ISSUE THREAD

**Issue by Flazso** [Nexus-Mods/Nexus-Mod-Manager#651] opened 2018-10-23 18:48 UTC
**Describe the bug** 
i recently installed fallout 4 vr and though i need to mod this thing so i install nmm at first it says i there is esb file or something like that and i fix that with a reinstall and now it just crashes every time i launch nmm i tried the antivirus thing but all i have is windows defender which normally servers me well but even after disabling it, and reinstalling several times it still refuses to work i would be grateful to any help

**Environment**
 NMM version: _0.65.2
Mod(s) used: no mods installed

**To Reproduce**
 i have no clue how one would reproduce this

**Additional information** 
thats all i got in terms of info in the issue
[TraceLog20181023143618.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2507567/TraceLog20181023143618.txt)

**Comment by squid-box** [comment] 2018-10-23 21:05
It's a duplicate of #300. If you install [the latest version of NMM](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases) you'll get proper support for FO4VR in NMM and won't have to move files around (which is what causes this crash).

**Closed as completed** 2019-02-15 17:27 UTC
Labels: duplicate
