### ISSUE TITLE
Nexus Mod Manager system.invalidcastexception

### ISSUE THREAD

**Issue by swashbuckler11** [Nexus-Mods/Nexus-Mod-Manager#477] opened 2018-07-09 05:11 UTC
hello im new to this site but im looking for answers this bug has been ruining my days of playing skyrim coz the mods that i have (over 47 mods) cannot be used i finally got rid of the bug with the updating issue and now i have encountered a new bug which is just as annoying. This bug happens when you freshly reinstall NMM scan your games like exp skyrim in my case and try to create a mod file for it comes up with these errors: 
![bs](https://user-images.githubusercontent.com/40975792/42431668-50f8e024-838a-11e8-9329-2e161abefbf2.PNG)

if anyone has a fix for this please help me

**Comment by squid-box** [comment] 2018-07-09 08:09
Duplicate of #465.

**Comment by squid-box** [comment] 2018-07-10 19:16
There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

If it doesn't work, please let us know in #465.

**Closed as completed by squid-box** 2018-07-10 19:16 UTC
Labels: duplicate
