### ISSUE TITLE
Please help solve this problem

### ISSUE THREAD

**Issue by ZeMamut** [Nexus-Mods/Nexus-Mod-Manager#386] opened 2018-06-09 01:22 UTC
**Describe the bug** 
when i opened NMM, It always encounter an error

**Environment**
- NMM version: 0.65.2.0

**To Reproduce**
whenever i tried to open game profiles (i don't know what it's called) from NMM

**Additional information** 
[TraceLog20180609082424.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2086529/TraceLog20180609082424.txt)
![2018-06-09](https://user-images.githubusercontent.com/40077606/41186374-68d39e10-6bbf-11e8-9566-f3fad1cc5478.png)

(sorry for bad english)

**Comment by squid-box** [comment] 2018-06-09 07:39
According to the log this is the same root cause as #389 (somehow the NMM settings file is already open/in use when NMM tries to save a setting (likely the current game mode in your case)), so I'll close this issue as a duplicate, but please check #389 for any progress made.

**Closed as completed by squid-box** 2018-06-09 07:39 UTC
Labels: duplicate

**Comment by ZeMamut** [comment] 2018-06-09 08:18
So, how's the progress?
